# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LGJBk46N9SjqStqgusBrgBbVgjyq7mld
"""

# ===============================================================
# 1. IMPORT LIBRARIES
# ===============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

import tensorflow as tf
from tensorflow.keras import layers, Model, Input

import statsmodels.api as sm


# ===============================================================
# 2. GENERATE SYNTHETIC DATASET (trend + seasonality + noise)
# ===============================================================
np.random.seed(42)

time = np.arange(0, 600)

trend = 0.05 * time                          # upward trend
seasonal = 20 * np.sin(2 * np.pi * time/50)  # periodic 50-step seasonality
noise = np.random.normal(0, 3, size=len(time))

series = trend + seasonal + noise

plt.figure(figsize=(12,4))
plt.plot(time, series)
plt.title("Synthetic Time Series Dataset")
plt.show()


# ===============================================================
# 3. SCALING
# ===============================================================
scaler = MinMaxScaler()
series_scaled = scaler.fit_transform(series.reshape(-1,1))


# ===============================================================
# 4. WINDOWING FUNCTION
# ===============================================================
def create_windows(data, window_size, horizon=1):
    X, y = [], []
    for i in range(len(data) - window_size - horizon):
        X.append(data[i:i+window_size])
        y.append(data[i+window_size:i+window_size+horizon])
    return np.array(X), np.array(y)

WINDOW = 40
HORIZON = 1

X, y = create_windows(series_scaled, WINDOW, HORIZON)
X = X.squeeze(-1)
y = y.squeeze(-1)

split = int(len(X) * 0.8)

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]


# ===============================================================
# 5. CUSTOM ATTENTION LAYER
# ===============================================================
class AttentionLayer(layers.Layer):
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def call(self, inputs):
        # inputs → [batch, timesteps, features]
        score = tf.keras.activations.tanh(inputs)
        attention_weights = tf.keras.activations.softmax(score, axis=1)
        context_vector = attention_weights * inputs
        context_vector = tf.reduce_sum(context_vector, axis=1)
        return context_vector


# ===============================================================
# 6. LSTM + ATTENTION MODEL
# ===============================================================
def build_attention_model(window_size):
    inputs = Input(shape=(window_size, 1))
    lstm_out = layers.LSTM(64, return_sequences=True)(inputs)
    context = AttentionLayer()(lstm_out)
    dense = layers.Dense(32, activation='relu')(context)
    outputs = layers.Dense(1)(dense)

    model = Model(inputs, outputs)
    model.compile(optimizer='adam', loss='mse')
    return model

X_train_dl = X_train.reshape(X_train.shape[0], WINDOW, 1)
X_test_dl = X_test.reshape(X_test.shape[0], WINDOW, 1)

model = build_attention_model(WINDOW)
model.summary()

history = model.fit(
    X_train_dl, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)


# ===============================================================
# 7. DEEP LEARNING MODEL PREDICTIONS
# ===============================================================
y_pred_dl = model.predict(X_test_dl)
y_pred_dl = scaler.inverse_transform(y_pred_dl)
y_test_inv = scaler.inverse_transform(y_test.reshape(-1,1))


# ===============================================================
# 8. BASELINE: SARIMA MODEL
# ===============================================================
# The SARIMA model's training data should correspond to the data BEFORE the DL test set.
# The DL test set (y_test) starts at index 'split' of the windowed data,
# which corresponds to 'split + WINDOW' in the original series.
# The forecast length for SARIMA should match the length of y_test.

sarima_train_end_index = split + WINDOW
sarima_forecast_steps = len(y_test)

sarima_model = sm.tsa.statespace.SARIMAX(
    series[:sarima_train_end_index],
    order=(2,1,2),
    seasonal_order=(1,1,1,50)
).fit(disp=False)

sarima_forecast_scaled = sarima_model.forecast(sarima_forecast_steps)
sarima_forecast = scaler.inverse_transform(sarima_forecast_scaled.reshape(-1,1))


# ===============================================================
# 9. EVALUATION METRICS
# ===============================================================
def MAPE(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

metrics = {
    "DL_RMSE": np.sqrt(mean_squared_error(y_test_inv, y_pred_dl)),
    "DL_MAE": mean_absolute_error(y_test_inv, y_pred_dl),
    "DL_MAPE": MAPE(y_test_inv, y_pred_dl),

    "SARIMA_RMSE": np.sqrt(mean_squared_error(y_test_inv, sarima_forecast)),
    "SARIMA_MAE": mean_absolute_error(y_test_inv, sarima_forecast),
    "SARIMA_MAPE": MAPE(y_test_inv, sarima_forecast),
}

print("\n===== MODEL PERFORMANCE =====")
for k, v in metrics.items():
    print(f"{k}: {v:.4f}")


# ===============================================================
# 10. FORECAST PLOT
# ===============================================================
plt.figure(figsize=(12,6))
plt.plot(y_test_inv, label="Actual", linewidth=2)
plt.plot(y_pred_dl, label="LSTM + Attention", linestyle='--')
plt.plot(sarima_forecast, label="SARIMA Baseline", linestyle=':')
plt.legend()
plt.title("Forecast Comparison")
plt.show()